set_property PACKAGE_PIN E3 [get_ports CLK100MHZ]
set_property IOSTANDART LVCMOS33 [get_ports CLK100MHZ]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports CLK100MHZ]

#7 segment display
set_property PACKAGE_PIN T10	 [get_ports {SEG[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[0]}]
set_property PACKAGE_PIN R10 	 [get_ports {SEG[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[1]}]
set_property PACKAGE_PIN K16 	 [get_ports {SEG[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[2]}]
set_property PACKAGE_PIN K13 	 [get_ports {SEG[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[3]}]
set_property PACKAGE_PIN P15 	 [get_ports {SEG[4]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[4]}]
set_property PACKAGE_PIN T11 	 [get_ports {SEG[5]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[5]}]
set_property PACKAGE_PIN L18 	 [get_ports {SEG[6]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[6]}]
set_property PACKAGE_PIN H15 	 [get_ports {SEG[7]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[7]}]

set_property PACKAGE_PIN J17 	 [get_ports {AN[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]
set_property PACKAGE_PIN J18 	 [get_ports {AN[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property PACKAGE_PIN T9 	 [get_ports {AN[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property PACKAGE_PIN J14 	 [get_ports {AN[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
set_property PACKAGE_PIN P14 	 [get_ports {AN[4]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {AN[4]}]
set_property PACKAGE_PIN T14 	 [get_ports {AN[5]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {AN[5]}]
set_property PACKAGE_PIN K2 	 [get_ports {AN[6]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {AN[6]}]
set_property PACKAGE_PIN U13 	 [get_ports {AN[7]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {AN[7]}]

#Sensor
set_property PACKAGE_PIN C14 	 [get_ports {TMP_SCL}]					
set_property IOSTANDARD LVCMOS33 [get_ports {TMP_SCL}]

set_property PACKAGE_PIN C15 	 [get_ports {TMP_SDA}]					
set_property IOSTANDARD LVCMOS33 [get_ports {TMP_SDA}]